version: "3.9"
services:
    api:
        container_name: gerenciador-jogos-api
        build: .
        ports:
            - "5050:80"
        depends_on:
            - db
    db:
        container_name: gerenciador-jogos-db
        build:
            context: .
            dockerfile: scripts/Dockerfile        
        ports:
            - "6060:1433"